-- =====================================================================
-- EstimateAI — PostgreSQL 16 schema (design reference)
-- In the application this is managed by Alembic migrations; this file is
-- the reviewed source of truth for the initial migration.
-- Conventions:
--   * UUID PKs generated by the application (UUIDv7).
--   * Money numeric(16,2) INR; rates numeric(14,2); quantity numeric(18,3)
--     with an unrounded numeric(28,10) companion where calculations occur.
--   * Every tenant-owned table carries organization_id for scoping.
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ---------------------------------------------------------------------
-- Enumerations
-- ---------------------------------------------------------------------
CREATE TYPE provenance AS ENUM (
  'user_entered', 'ai_extracted', 'ai_suggested', 'default_accepted',
  'document_extracted', 'drawing_derived', 'rate_database', 'calculated'
);
CREATE TYPE org_role       AS ENUM ('owner', 'admin', 'member');
CREATE TYPE project_role   AS ENUM ('admin', 'professional', 'contractor', 'viewer');
CREATE TYPE version_status AS ENUM ('draft', 'frozen');
CREATE TYPE job_status     AS ENUM ('queued', 'running', 'needs_input', 'succeeded', 'failed', 'cancelled');
CREATE TYPE rate_verification AS ENUM ('demo', 'user_entered', 'imported_unverified', 'verified_official');
CREATE TYPE export_format  AS ENUM ('pdf', 'xlsx', 'docx');
CREATE TYPE unit_dimension AS ENUM ('length', 'area', 'volume', 'mass', 'count', 'lump_sum', 'other');

-- ---------------------------------------------------------------------
-- Identity & tenancy
-- ---------------------------------------------------------------------
CREATE TABLE users (
  id               uuid PRIMARY KEY,
  email            citext NOT NULL UNIQUE,
  email_verified_at timestamptz,
  password_hash    text,                       -- NULL for Google-only accounts
  full_name        text NOT NULL,
  phone            text,
  platform_role    text NOT NULL DEFAULT 'user' CHECK (platform_role IN ('user','admin')),
  locale           text NOT NULL DEFAULT 'en-IN',
  is_active        boolean NOT NULL DEFAULT true,
  last_login_at    timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE oauth_accounts (
  id               uuid PRIMARY KEY,
  user_id          uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider         text NOT NULL,              -- 'google'
  provider_subject text NOT NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (provider, provider_subject)
);

CREATE TABLE refresh_tokens (
  id               uuid PRIMARY KEY,
  user_id          uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash       text NOT NULL UNIQUE,       -- SHA-256 of the opaque token
  family_id        uuid NOT NULL,              -- rotation family for reuse detection
  expires_at       timestamptz NOT NULL,
  revoked_at       timestamptz,
  user_agent       text,
  ip_address       inet,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_refresh_tokens_user ON refresh_tokens(user_id);

CREATE TABLE organizations (
  id               uuid PRIMARY KEY,
  name             text NOT NULL,
  is_personal      boolean NOT NULL DEFAULT false,
  gstin            text,
  state_code       text,                        -- e.g. 'TS' → drives CGST+SGST vs IGST default
  logo_storage_key text,
  address          text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE organization_members (
  organization_id  uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id          uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role             org_role NOT NULL DEFAULT 'member',
  created_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (organization_id, user_id)
);

-- ---------------------------------------------------------------------
-- Units
-- ---------------------------------------------------------------------
CREATE TABLE units (
  code             text PRIMARY KEY,           -- 'm','km','sqm','sqft','cum','cuft','kg','mt','nos','ls','rmt','set'
  display_name     text NOT NULL,              -- 'Cum', 'Sq.m', 'Rmt'
  dimension        unit_dimension NOT NULL,
  is_canonical     boolean NOT NULL DEFAULT false, -- one per dimension: m, sqm, cum, kg
  decimal_places   smallint NOT NULL DEFAULT 3,
  aliases          text[] NOT NULL DEFAULT '{}' -- 'cu.m','m3','cubic metre' … for parsing
);

CREATE TABLE unit_conversions (
  from_unit        text NOT NULL REFERENCES units(code),
  to_unit          text NOT NULL REFERENCES units(code),
  factor           numeric(28,12) NOT NULL,     -- to = from × factor + offset
  "offset"         numeric(28,12) NOT NULL DEFAULT 0,
  source_note      text,
  PRIMARY KEY (from_unit, to_unit),
  CHECK (from_unit <> to_unit),
  CHECK (factor > 0)
);

-- ---------------------------------------------------------------------
-- Projects
-- ---------------------------------------------------------------------
CREATE TABLE work_categories (
  id               uuid PRIMARY KEY,
  organization_id  uuid REFERENCES organizations(id) ON DELETE CASCADE, -- NULL = global
  project_type     text NOT NULL,
  name             text NOT NULL,
  is_active        boolean NOT NULL DEFAULT true,
  UNIQUE NULLS NOT DISTINCT (organization_id, project_type, name)
);

CREATE TABLE projects (
  id               uuid PRIMARY KEY,
  organization_id  uuid NOT NULL REFERENCES organizations(id),
  name             text NOT NULL,
  project_type     text NOT NULL CHECK (project_type IN (
                     'building','road','drain','culvert','bridge','irrigation','canal','tank',
                     'lift_irrigation','water_supply','sewerage','electrical','other')),
  work_category_id uuid REFERENCES work_categories(id),
  client_department text,
  location         text,
  district         text,
  state            text NOT NULL DEFAULT 'Telangana',
  estimated_value  numeric(16,2),
  description      text,
  engineer_name    text,
  contractor_name  text,
  reference_number text,
  project_date     date,
  status           text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','in_progress','completed','archived')),
  search_vector    tsvector GENERATED ALWAYS AS (
                     to_tsvector('simple', coalesce(name,'') || ' ' || coalesce(reference_number,'') || ' ' ||
                                           coalesce(location,'') || ' ' || coalesce(district,''))) STORED,
  created_by       uuid NOT NULL REFERENCES users(id),
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  deleted_at       timestamptz
);
CREATE INDEX ix_projects_org ON projects(organization_id) WHERE deleted_at IS NULL;
CREATE INDEX ix_projects_search ON projects USING gin(search_vector);

CREATE TABLE project_members (
  project_id       uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id          uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role             project_role NOT NULL,
  added_by         uuid REFERENCES users(id),
  created_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (project_id, user_id)
);

-- ---------------------------------------------------------------------
-- Estimates, versions, BOQ, measurements, calculations
-- ---------------------------------------------------------------------
CREATE TABLE estimates (
  id               uuid PRIMARY KEY,
  organization_id  uuid NOT NULL REFERENCES organizations(id),
  project_id       uuid NOT NULL REFERENCES projects(id),
  estimate_number  text NOT NULL,
  title            text NOT NULL,
  prepared_by      text,
  checked_by       text,
  approved_by      text,
  created_by       uuid NOT NULL REFERENCES users(id),
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  deleted_at       timestamptz,
  UNIQUE (organization_id, estimate_number)
);
CREATE INDEX ix_estimates_project ON estimates(project_id);

CREATE TABLE estimate_versions (
  id               uuid PRIMARY KEY,
  organization_id  uuid NOT NULL REFERENCES organizations(id),
  estimate_id      uuid NOT NULL REFERENCES estimates(id) ON DELETE CASCADE,
  version_no       integer NOT NULL,
  status           version_status NOT NULL DEFAULT 'draft',
  change_note      text,                        -- "Width changed from 5 m to 5.5 m"
  parent_version_id uuid REFERENCES estimate_versions(id),
  -- GST configuration (see docs 01 §1.6). Example:
  -- {"applicable":true,"mode":"exclusive","type":"intra","cgst_pct":9,"sgst_pct":9,"igst_pct":0,"base":"after_charges"}
  gst_config       jsonb NOT NULL DEFAULT '{"applicable":false}',
  rounding_config  jsonb NOT NULL DEFAULT '{"quantity_dp":3,"amount_dp":2,"grand_total":"nearest_rupee"}',
  totals_snapshot  jsonb,                       -- filled on freeze; recomputed live for drafts
  engine_version   text,
  frozen_at        timestamptz,
  frozen_by        uuid REFERENCES users(id),
  created_by       uuid NOT NULL REFERENCES users(id),
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (estimate_id, version_no)
);
-- At most one draft per estimate.
CREATE UNIQUE INDEX ux_one_draft_per_estimate ON estimate_versions(estimate_id) WHERE status = 'draft';

CREATE TABLE estimate_sections (
  id               uuid PRIMARY KEY,
  organization_id  uuid NOT NULL REFERENCES organizations(id),
  version_id       uuid NOT NULL REFERENCES estimate_versions(id) ON DELETE CASCADE,
  line_key         uuid NOT NULL,
  title            text NOT NULL,
  sequence         integer NOT NULL,
  UNIQUE (version_id, line_key)
);

CREATE TABLE calculation_templates (
  id               text NOT NULL,               -- 'road_layer'
  version          integer NOT NULL,
  name             text NOT NULL,
  category         text NOT NULL,               -- 'road','building','irrigation','generic'
  expression       text NOT NULL,               -- 'length * width * thickness'
  parameters       jsonb NOT NULL,              -- [{"name":"length","dimension":"length","required":true,"default":null}, ...]
  output_unit      text NOT NULL REFERENCES units(code),
  description      text,
  is_active        boolean NOT NULL DEFAULT true,
  created_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id, version)
);

CREATE TABLE quantity_inputs (                  -- named project parameters
  id               uuid PRIMARY KEY,
  organization_id  uuid NOT NULL REFERENCES organizations(id),
  version_id       uuid NOT NULL REFERENCES estimate_versions(id) ON DELETE CASCADE,
  line_key         uuid NOT NULL,
  name             text NOT NULL CHECK (name ~ '^[a-z][a-z0-9_]{0,62}$'),
  label            text NOT NULL,               -- "GSB thickness"
  value            numeric(28,10),              -- NULL = missing, blocks calculation
  unit_code        text REFERENCES units(code),
  provenance       provenance NOT NULL,
  source_text      text,                        -- span of user/document text it came from
  source_document_id uuid,
  confirmed_by     uuid REFERENCES users(id),
  confirmed_at     timestamptz,
  UNIQUE (version_id, name)
);

CREATE TABLE rate_sources (
  id               uuid PRIMARY KEY,
  organization_id  uuid REFERENCES organizations(id), -- NULL = platform-wide
  state            text NOT NULL,
  department       text NOT NULL,              -- 'R&B', 'I&CAD', 'PR' …
  sor_name         text NOT NULL,
  year             text NOT NULL CHECK (year ~ '^\d{4}-\d{2}$'),  -- '2026-27'
  effective_from   date NOT NULL,
  effective_to     date,
  verification_status rate_verification NOT NULL,
  source_reference text,                        -- G.O. number / document title
  source_document_id uuid,                      -- uploaded official source, if any
  notes            text,
  created_by       uuid REFERENCES users(id),
  created_at       timestamptz NOT NULL DEFAULT now(),
  CHECK (effective_to IS NULL OR effective_to >= effective_from),
  -- 'verified_official' requires an uploaded source document.
  CHECK (verification_status <> 'verified_official' OR source_document_id IS NOT NULL)
);

CREATE TABLE rate_import_batches (
  id               uuid PRIMARY KEY,
  rate_source_id   uuid NOT NULL REFERENCES rate_sources(id) ON DELETE CASCADE,
  filename         text NOT NULL,
  row_count        integer NOT NULL DEFAULT 0,
  error_count      integer NOT NULL DEFAULT 0,
  errors           jsonb,
  status           text NOT NULL,
  created_by       uuid NOT NULL REFERENCES users(id),
  created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE rate_items (
  id               uuid PRIMARY KEY,
  rate_source_id   uuid NOT NULL REFERENCES rate_sources(id) ON DELETE CASCADE,
  import_batch_id  uuid REFERENCES rate_import_batches(id) ON DELETE SET NULL,
  item_code        text NOT NULL,
  description      text NOT NULL,
  specification    text,
  unit_code        text NOT NULL REFERENCES units(code),
  basic_rate       numeric(14,2) NOT NULL CHECK (basic_rate >= 0),
  gst_pct          numeric(7,4),
  total_rate       numeric(14,2) NOT NULL CHECK (total_rate >= 0),
  search_vector    tsvector GENERATED ALWAYS AS (
                     to_tsvector('english', coalesce(item_code,'') || ' ' || coalesce(description,''))) STORED,
  created_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (rate_source_id, item_code)
);
CREATE INDEX ix_rate_items_fts  ON rate_items USING gin(search_vector);
CREATE INDEX ix_rate_items_trgm ON rate_items USING gin(description gin_trgm_ops);

CREATE TABLE ai_generations (
  id               uuid PRIMARY KEY,
  organization_id  uuid NOT NULL REFERENCES organizations(id),
  user_id          uuid NOT NULL REFERENCES users(id),
  project_id       uuid REFERENCES projects(id),
  purpose          text NOT NULL,              -- 'extract_parameters','document_boq','assistant','explain_item'
  prompt_id        text NOT NULL,
  prompt_version   integer NOT NULL,
  model            text NOT NULL,
  input_hash       text NOT NULL,              -- SHA-256 of normalised input → response cache key
  input_text       text,
  raw_output       jsonb,
  validated_output jsonb,
  validation_errors jsonb,
  status           job_status NOT NULL,
  input_tokens     integer NOT NULL DEFAULT 0,
  output_tokens    integer NOT NULL DEFAULT 0,
  cache_read_tokens integer NOT NULL DEFAULT 0,
  cache_write_tokens integer NOT NULL DEFAULT 0,
  cost_usd         numeric(12,6) NOT NULL DEFAULT 0,
  latency_ms       integer,
  served_from_cache boolean NOT NULL DEFAULT false,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_ai_generations_org_time ON ai_generations(organization_id, created_at DESC);
CREATE INDEX ix_ai_generations_cache ON ai_generations(prompt_id, prompt_version, model, input_hash);

CREATE TABLE boq_items (
  id               uuid PRIMARY KEY,
  organization_id  uuid NOT NULL REFERENCES organizations(id),
  version_id       uuid NOT NULL REFERENCES estimate_versions(id) ON DELETE CASCADE,
  section_id       uuid NOT NULL REFERENCES estimate_sections(id) ON DELETE CASCADE,
  line_key         uuid NOT NULL,              -- stable across versions → diffing
  sequence         integer NOT NULL,
  item_no          text,
  description      text NOT NULL,
  specification    text,
  unit_code        text REFERENCES units(code),
  quantity         numeric(18,3),
  quantity_raw     numeric(28,10),
  quantity_source  text NOT NULL DEFAULT 'manual' CHECK (quantity_source IN ('manual','measurements')),
  rate             numeric(14,2),
  rate_source_type text CHECK (rate_source_type IN ('manual','rate_database','document')),
  rate_item_id     uuid REFERENCES rate_items(id) ON DELETE SET NULL,
  rate_snapshot    jsonb,                       -- copy of source/sor/year/code at selection time
  amount           numeric(16,2),              -- = round2(quantity × rate), maintained by service
  remarks          text,
  provenance       provenance NOT NULL,
  ai_generation_id uuid REFERENCES ai_generations(id),
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (version_id, line_key)
);
CREATE INDEX ix_boq_items_section ON boq_items(section_id, sequence);
CREATE INDEX ix_boq_items_desc_trgm ON boq_items USING gin(description gin_trgm_ops);

CREATE TABLE estimate_items (                   -- measurement lines of the detailed estimate
  id               uuid PRIMARY KEY,
  organization_id  uuid NOT NULL REFERENCES organizations(id),
  version_id       uuid NOT NULL REFERENCES estimate_versions(id) ON DELETE CASCADE,
  boq_item_id      uuid NOT NULL REFERENCES boq_items(id) ON DELETE CASCADE,
  line_key         uuid NOT NULL,
  sequence         integer NOT NULL,
  description      text NOT NULL,              -- "Ch. 0–500, carriageway"
  nos              numeric(18,4) NOT NULL DEFAULT 1,
  length           numeric(18,4),
  breadth          numeric(18,4),
  depth_height     numeric(18,4),
  dimension_unit   text REFERENCES units(code) DEFAULT 'm',
  quantity         numeric(18,3),
  quantity_raw     numeric(28,10),
  is_deduction     boolean NOT NULL DEFAULT false,
  provenance       provenance NOT NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (version_id, line_key)
);
CREATE INDEX ix_estimate_items_boq ON estimate_items(boq_item_id, sequence);

CREATE TABLE calculations (
  id               uuid PRIMARY KEY,
  organization_id  uuid NOT NULL REFERENCES organizations(id),
  estimate_item_id uuid NOT NULL UNIQUE REFERENCES estimate_items(id) ON DELETE CASCADE,
  template_id      text,
  template_version integer,
  expression       text NOT NULL,              -- 'length * width * thickness' or custom
  input_parameters jsonb NOT NULL,             -- {"length":{"value":"500","unit":"m","provenance":"ai_extracted","ref":"road_length"}, ...}
  substituted      text NOT NULL,              -- '500 × 5.5 × 0.15'
  steps            jsonb NOT NULL,             -- ordered breakdown for "View Calculation"
  result_raw       numeric(28,10) NOT NULL,
  result_unit      text NOT NULL REFERENCES units(code),
  engine_version   text NOT NULL,
  calculated_at    timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (template_id, template_version) REFERENCES calculation_templates(id, version)
);

CREATE TABLE estimate_charges (
  id               uuid PRIMARY KEY,
  organization_id  uuid NOT NULL REFERENCES organizations(id),
  version_id       uuid NOT NULL REFERENCES estimate_versions(id) ON DELETE CASCADE,
  line_key         uuid NOT NULL,
  name             text NOT NULL,              -- 'Contingencies'
  kind             text NOT NULL CHECK (kind IN ('contingency','work_charged_establishment','labour_cess',
                                                 'seigniorage','royalty','other')),
  percentage       numeric(7,4),
  fixed_amount     numeric(16,2),
  applies_to       jsonb NOT NULL DEFAULT '{"base":"works_subtotal"}', -- or {"base":"sections","section_keys":[...]}
  enabled          boolean NOT NULL DEFAULT true,
  sequence         integer NOT NULL,
  CHECK ((percentage IS NULL) <> (fixed_amount IS NULL)),
  UNIQUE (version_id, line_key)
);

-- ---------------------------------------------------------------------
-- Documents
-- ---------------------------------------------------------------------
CREATE TABLE documents (
  id               uuid PRIMARY KEY,
  organization_id  uuid NOT NULL REFERENCES organizations(id),
  project_id       uuid REFERENCES projects(id),
  kind             text NOT NULL DEFAULT 'general' CHECK (kind IN
                     ('general','boq','estimate','drawing','site_photo','sor_source','logo')),
  original_filename text NOT NULL,
  mime_type        text NOT NULL,
  size_bytes       bigint NOT NULL,
  sha256           text NOT NULL,
  storage_key      text NOT NULL UNIQUE,
  page_count       integer,
  scan_status      text NOT NULL DEFAULT 'pending' CHECK (scan_status IN ('pending','clean','infected','error')),
  has_text_layer   boolean,
  processing_status text NOT NULL DEFAULT 'uploaded',
  processing_error text,
  uploaded_by      uuid NOT NULL REFERENCES users(id),
  created_at       timestamptz NOT NULL DEFAULT now(),
  deleted_at       timestamptz
);
CREATE INDEX ix_documents_project ON documents(project_id) WHERE deleted_at IS NULL;

CREATE TABLE document_chunks (
  id               uuid PRIMARY KEY,
  organization_id  uuid NOT NULL REFERENCES organizations(id),
  document_id      uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  page_no          integer NOT NULL,
  chunk_no         integer NOT NULL,
  text_content     text NOT NULL,
  extraction_method text NOT NULL CHECK (extraction_method IN ('text_layer','ocr','spreadsheet','docx')),
  ocr_confidence   numeric(5,4),
  search_vector    tsvector GENERATED ALWAYS AS (to_tsvector('simple', text_content)) STORED,
  UNIQUE (document_id, page_no, chunk_no)
);
CREATE INDEX ix_document_chunks_fts ON document_chunks USING gin(search_vector);

-- ---------------------------------------------------------------------
-- Jobs, exports, audit, notifications
-- ---------------------------------------------------------------------
CREATE TABLE jobs (
  id               uuid PRIMARY KEY,
  organization_id  uuid NOT NULL REFERENCES organizations(id),
  user_id          uuid NOT NULL REFERENCES users(id),
  kind             text NOT NULL,
  status           job_status NOT NULL DEFAULT 'queued',
  progress         smallint NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),
  stage            text,
  subject_type     text,
  subject_id       uuid,
  result           jsonb,
  error_code       text,
  error_message    text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_jobs_user_time ON jobs(user_id, created_at DESC);

CREATE TABLE exports (
  id               uuid PRIMARY KEY,
  organization_id  uuid NOT NULL REFERENCES organizations(id),
  version_id       uuid NOT NULL REFERENCES estimate_versions(id) ON DELETE CASCADE,
  format           export_format NOT NULL,
  options          jsonb NOT NULL DEFAULT '{}', -- sheets/sections included, letterhead, signatories
  job_id           uuid REFERENCES jobs(id),
  storage_key      text,
  size_bytes       bigint,
  created_by       uuid NOT NULL REFERENCES users(id),
  created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE audit_logs (
  id               bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  organization_id  uuid,
  actor_user_id    uuid,
  actor_display    text,                        -- name at time of action ("Mahesh")
  entity_type      text NOT NULL,              -- 'boq_item','quantity_input','estimate_version',…
  entity_id        uuid,
  project_id       uuid,
  version_id       uuid,
  action           text NOT NULL,              -- 'update','create','delete','freeze','accept_default','select_rate'
  field            text,
  old_value        jsonb,
  new_value        jsonb,
  request_id       text,
  ip_address       inet,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_audit_project_time ON audit_logs(project_id, created_at DESC);
CREATE INDEX ix_audit_entity ON audit_logs(entity_type, entity_id);
-- Append-only: application role gets INSERT/SELECT only (REVOKE UPDATE, DELETE in migration).

CREATE TABLE notifications (
  id               uuid PRIMARY KEY,
  user_id          uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind             text NOT NULL,
  title            text NOT NULL,
  body             text,
  link             text,
  read_at          timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_notifications_user_unread ON notifications(user_id) WHERE read_at IS NULL;

-- ---------------------------------------------------------------------
-- Billing
-- ---------------------------------------------------------------------
CREATE TABLE plans (
  code             text PRIMARY KEY,            -- 'free','starter','pro','business'
  name             text NOT NULL,
  price_inr_monthly numeric(10,2) NOT NULL,
  price_inr_yearly numeric(10,2),
  razorpay_plan_id_monthly text,
  razorpay_plan_id_yearly  text,
  -- {"ai_generations_per_period":50,"projects":25,"doc_pages_per_period":100,"max_upload_mb":25,"seats":1}
  limits           jsonb NOT NULL,
  -- {"export_pdf":true,"export_xlsx":true,"export_docx":false,"rate_database":false,"team":false}
  features         jsonb NOT NULL,
  is_active        boolean NOT NULL DEFAULT true,
  sort_order       smallint NOT NULL DEFAULT 0
);

CREATE TABLE subscriptions (
  id               uuid PRIMARY KEY,
  organization_id  uuid NOT NULL REFERENCES organizations(id),
  plan_code        text NOT NULL REFERENCES plans(code),
  status           text NOT NULL CHECK (status IN ('active','trialing','pending','halted','cancelled','expired')),
  razorpay_subscription_id text UNIQUE,
  razorpay_customer_id text,
  current_period_start timestamptz NOT NULL,
  current_period_end   timestamptz NOT NULL,
  cancel_at_period_end boolean NOT NULL DEFAULT false,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_one_live_subscription ON subscriptions(organization_id)
  WHERE status IN ('active','trialing','pending','halted');

CREATE TABLE payments (
  id               uuid PRIMARY KEY,
  organization_id  uuid NOT NULL REFERENCES organizations(id),
  subscription_id  uuid REFERENCES subscriptions(id),
  razorpay_payment_id text UNIQUE,
  razorpay_invoice_id text,
  amount_inr       numeric(12,2) NOT NULL,
  gst_amount_inr   numeric(12,2),
  method           text,                        -- 'upi','card','netbanking'
  status           text NOT NULL,
  raw              jsonb,
  created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE webhook_events (
  id               text PRIMARY KEY,            -- provider event id → idempotency
  provider         text NOT NULL,
  event_type       text NOT NULL,
  payload          jsonb NOT NULL,
  signature_valid  boolean NOT NULL,
  processed_at     timestamptz,
  error            text,
  received_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE usage_counters (
  organization_id  uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  metric           text NOT NULL,              -- 'ai_generations','doc_pages','exports'
  period_start     date NOT NULL,
  used             integer NOT NULL DEFAULT 0 CHECK (used >= 0),
  PRIMARY KEY (organization_id, metric, period_start)
);

-- ---------------------------------------------------------------------
-- Settings, prompts, feature flags
-- ---------------------------------------------------------------------
CREATE TABLE settings (
  scope            text NOT NULL CHECK (scope IN ('platform','organization','user')),
  scope_id         uuid,                        -- NULL for platform
  key              text NOT NULL,              -- 'gst.default', 'charges.default', 'export.letterhead'
  value            jsonb NOT NULL,
  updated_by       uuid REFERENCES users(id),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE NULLS NOT DISTINCT (scope, scope_id, key)
);

CREATE TABLE prompt_templates (
  id               text NOT NULL,               -- 'extract_parameters'
  version          integer NOT NULL,
  purpose          text NOT NULL,
  model_tier       text NOT NULL CHECK (model_tier IN ('fast','standard','deep')),
  system_prompt    text NOT NULL,
  output_schema    jsonb,
  is_active        boolean NOT NULL DEFAULT false,
  eval_score       numeric(5,4),               -- last golden-set score before activation
  created_by       uuid REFERENCES users(id),
  created_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id, version)
);
CREATE UNIQUE INDEX ux_prompt_active ON prompt_templates(id) WHERE is_active;

CREATE TABLE feature_flags (
  key              text PRIMARY KEY,
  enabled          boolean NOT NULL DEFAULT false,
  rules            jsonb NOT NULL DEFAULT '{}', -- {"plans":["pro","business"],"org_ids":[...]}
  description      text,
  updated_at       timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- Guard: frozen versions are immutable
-- ---------------------------------------------------------------------
CREATE FUNCTION forbid_frozen_version_change() RETURNS trigger AS $$
DECLARE v_status version_status;
BEGIN
  SELECT status INTO v_status FROM estimate_versions
   WHERE id = COALESCE(NEW.version_id, OLD.version_id);
  IF v_status = 'frozen' THEN
    RAISE EXCEPTION 'VERSION_FROZEN' USING ERRCODE = 'check_violation';
  END IF;
  RETURN COALESCE(NEW, OLD);
END $$ LANGUAGE plpgsql;

CREATE TRIGGER trg_boq_items_frozen       BEFORE INSERT OR UPDATE OR DELETE ON boq_items
  FOR EACH ROW EXECUTE FUNCTION forbid_frozen_version_change();
CREATE TRIGGER trg_estimate_items_frozen  BEFORE INSERT OR UPDATE OR DELETE ON estimate_items
  FOR EACH ROW EXECUTE FUNCTION forbid_frozen_version_change();
CREATE TRIGGER trg_sections_frozen        BEFORE INSERT OR UPDATE OR DELETE ON estimate_sections
  FOR EACH ROW EXECUTE FUNCTION forbid_frozen_version_change();
CREATE TRIGGER trg_charges_frozen         BEFORE INSERT OR UPDATE OR DELETE ON estimate_charges
  FOR EACH ROW EXECUTE FUNCTION forbid_frozen_version_change();
CREATE TRIGGER trg_quantity_inputs_frozen BEFORE INSERT OR UPDATE OR DELETE ON quantity_inputs
  FOR EACH ROW EXECUTE FUNCTION forbid_frozen_version_change();

-- ---------------------------------------------------------------------
-- Seed: units & conversions (canonical: m, sqm, cum, kg)
-- ---------------------------------------------------------------------
INSERT INTO units (code, display_name, dimension, is_canonical, decimal_places, aliases) VALUES
  ('mm',   'mm',      'length', false, 0, '{millimetre,millimeter}'),
  ('cm',   'cm',      'length', false, 1, '{centimetre,centimeter}'),
  ('m',    'm',       'length', true,  3, '{metre,meter,mtr,mts,rm}'),
  ('km',   'km',      'length', false, 3, '{kilometre,kilometer,kms}'),
  ('ft',   'ft',      'length', false, 2, '{feet,foot}'),
  ('rmt',  'Rmt',     'length', false, 2, '{"running metre","r.m",rmt}'),
  ('sqm',  'Sq.m',    'area',   true,  2, '{sq.m,m2,"square metre",sqmt}'),
  ('sqft', 'Sq.ft',   'area',   false, 2, '{sq.ft,ft2,"square feet",sft}'),
  ('acre', 'Acre',    'area',   false, 4, '{acres}'),
  ('ha',   'Hectare', 'area',   false, 4, '{hectare,hectares}'),
  ('cum',  'Cum',     'volume', true,  3, '{cu.m,m3,"cubic metre"}'),
  ('cuft', 'Cft',     'volume', false, 2, '{cu.ft,ft3,cft,"cubic feet"}'),
  ('l',    'Litre',   'volume', false, 2, '{litre,liter,ltr}'),
  ('kg',   'Kg',      'mass',   true,  3, '{kilogram,kgs}'),
  ('qtl',  'Quintal', 'mass',   false, 3, '{quintal,quintals}'),
  ('mt',   'MT',      'mass',   false, 3, '{tonne,ton,tonnes,"metric tonne"}'),
  ('nos',  'Nos',     'count',  true,  0, '{no,number,numbers,each}'),
  ('set',  'Set',     'count',  false, 0, '{sets}'),
  ('ls',   'LS',      'lump_sum', true, 0, '{"lump sum",lumpsum}');

INSERT INTO unit_conversions (from_unit, to_unit, factor, source_note) VALUES
  ('mm',   'm',   0.001,          'SI'),
  ('cm',   'm',   0.01,           'SI'),
  ('km',   'm',   1000,           'SI'),
  ('ft',   'm',   0.3048,         'International foot (exact)'),
  ('rmt',  'm',   1,              'Running metre'),
  ('sqft', 'sqm', 0.09290304,     '0.3048² (exact)'),
  ('acre', 'sqm', 4046.8564224,   'International acre (exact)'),
  ('ha',   'sqm', 10000,          'SI'),
  ('cuft', 'cum', 0.028316846592, '0.3048³ (exact)'),
  ('l',    'cum', 0.001,          'SI'),
  ('qtl',  'kg',  100,            'Indian quintal'),
  ('mt',   'kg',  1000,           'Metric tonne');
-- Reverse and indirect conversions are derived by the unit service via the canonical unit;
-- they are not stored, to avoid inconsistent pairs.
