/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgot Password */
        post: operations["forgot_password_api_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend Verification */
        post: operations["resend_verification_api_v1_auth_resend_verification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Email */
        post: operations["verify_email_api_v1_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate */
        post: operations["calculate_api_v1_calculate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calculate/validate-expression": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Expression */
        post: operations["validate_expression_api_v1_calculate_validate_expression_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calculation-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["list_templates_api_v1_calculation_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_v1_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Me */
        patch: operations["patch_me_api_v1_me_patch"];
        trace?: never;
    };
    "/api/v1/organizations/{org_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Organization */
        get: operations["get_organization_api_v1_organizations__org_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Organization */
        patch: operations["patch_organization_api_v1_organizations__org_id__patch"];
        trace?: never;
    };
    "/api/v1/project-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Types */
        get: operations["project_types_api_v1_project_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_v1_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Patch Project */
        patch: operations["patch_project_api_v1_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Info */
        get: operations["system_info_api_v1_system_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Units */
        get: operations["list_units_api_v1_units_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/units/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Convert Units */
        post: operations["convert_units_api_v1_units_convert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Work Categories */
        get: operations["work_categories_api_v1_work_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CalculateIn */
        CalculateIn: {
            /** Expression */
            expression?: string | null;
            /** Output Unit */
            output_unit?: string | null;
            /** Parameters */
            parameters?: {
                [key: string]: components["schemas"]["ParamIn"];
            };
            /** Template Id */
            template_id?: string | null;
            /** Template Version */
            template_version?: number | null;
        };
        /** CalculationOut */
        CalculationOut: {
            /**
             * Check
             * @description Arithmetic and unit checks only; not a confirmation of engineering correctness.
             * @default Calculation check passed
             */
            check: string;
            /** Display */
            display: string;
            /** Engine Version */
            engine_version: string;
            /** Expression */
            expression: string;
            /** Inputs */
            inputs: components["schemas"]["ResolvedInputOut"][];
            /** Steps */
            steps: components["schemas"]["StepOut"][];
            /** Substituted */
            substituted: string;
            /** Template Id */
            template_id: string | null;
            /** Template Version */
            template_version: number | null;
            /** Unit */
            unit: string;
            /** Unit Display */
            unit_display: string;
            /** Value */
            value: string;
            /** Value Raw */
            value_raw: string;
        };
        /** CategoryOut */
        CategoryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Project Type */
            project_type: string;
        };
        /** ConvertIn */
        ConvertIn: {
            /** From Unit */
            from_unit: string;
            /** To Unit */
            to_unit: string;
            /**
             * Value
             * @description Number; strings keep full precision
             */
            value: string | number | null;
        };
        /** ConvertOut */
        ConvertOut: {
            /** Display */
            display: string;
            /** From Unit */
            from_unit: string;
            /** To Unit */
            to_unit: string;
            /** Value */
            value: string;
        };
        /** DashboardOut */
        DashboardOut: {
            /** Completed Projects */
            completed_projects: number;
            /** Draft Projects */
            draft_projects: number;
            /** In Progress Projects */
            in_progress_projects: number;
            /** Recent Documents */
            recent_documents: {
                [key: string]: unknown;
            }[];
            /** Recent Estimates */
            recent_estimates: {
                [key: string]: unknown;
            }[];
            /** Recent Projects */
            recent_projects: components["schemas"]["ProjectOut"][];
            subscription: components["schemas"]["SubscriptionOut"];
            /** Total Estimated Value */
            total_estimated_value: string;
            /** Total Estimated Value Display */
            total_estimated_value_display: string;
            /** Total Projects */
            total_projects: number;
            usage: components["schemas"]["UsageOut"];
        };
        /** Envelope[CalculationOut] */
        Envelope_CalculationOut_: {
            data: components["schemas"]["CalculationOut"];
            meta: components["schemas"]["Meta"];
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** Envelope[ConvertOut] */
        Envelope_ConvertOut_: {
            data: components["schemas"]["ConvertOut"];
            meta: components["schemas"]["Meta"];
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** Envelope[DashboardOut] */
        Envelope_DashboardOut_: {
            data: components["schemas"]["DashboardOut"];
            meta: components["schemas"]["Meta"];
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** Envelope[ExpressionOut] */
        Envelope_ExpressionOut_: {
            data: components["schemas"]["ExpressionOut"];
            meta: components["schemas"]["Meta"];
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** Envelope[MeOut] */
        Envelope_MeOut_: {
            data: components["schemas"]["MeOut"];
            meta: components["schemas"]["Meta"];
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** Envelope[Message] */
        Envelope_Message_: {
            data: components["schemas"]["Message"];
            meta: components["schemas"]["Meta"];
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** Envelope[OrganizationOut] */
        Envelope_OrganizationOut_: {
            data: components["schemas"]["OrganizationOut"];
            meta: components["schemas"]["Meta"];
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** Envelope[ProjectOut] */
        Envelope_ProjectOut_: {
            data: components["schemas"]["ProjectOut"];
            meta: components["schemas"]["Meta"];
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** Envelope[SystemInfo] */
        Envelope_SystemInfo_: {
            data: components["schemas"]["SystemInfo"];
            meta: components["schemas"]["Meta"];
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** Envelope[dict[str, bool]] */
        Envelope_dict_str__bool__: {
            /** Data */
            data: {
                [key: string]: boolean;
            };
            meta: components["schemas"]["Meta"];
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** Envelope[list[CategoryOut]] */
        Envelope_list_CategoryOut__: {
            /** Data */
            data: components["schemas"]["CategoryOut"][];
            meta: components["schemas"]["Meta"];
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** Envelope[list[Option]] */
        Envelope_list_Option__: {
            /** Data */
            data: components["schemas"]["Option"][];
            meta: components["schemas"]["Meta"];
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** Envelope[list[TemplateOut]] */
        Envelope_list_TemplateOut__: {
            /** Data */
            data: components["schemas"]["TemplateOut"][];
            meta: components["schemas"]["Meta"];
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** Envelope[list[UnitOut]] */
        Envelope_list_UnitOut__: {
            /** Data */
            data: components["schemas"]["UnitOut"][];
            meta: components["schemas"]["Meta"];
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** ExpressionIn */
        ExpressionIn: {
            /** Expression */
            expression: string;
        };
        /** ExpressionOut */
        ExpressionOut: {
            /** Expression Display */
            expression_display: string;
            /** Parameters */
            parameters: string[];
        };
        /** ForgotIn */
        ForgotIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MeOut */
        MeOut: {
            organization: components["schemas"]["OrganizationOut"];
            subscription: components["schemas"]["SubscriptionOut"];
            usage: components["schemas"]["UsageOut"];
            user: components["schemas"]["UserOut"];
        };
        /** MePatch */
        MePatch: {
            /** Full Name */
            full_name?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /** Message */
        Message: {
            /** Message */
            message: string;
        };
        /** Meta */
        Meta: {
            /** Request Id */
            request_id?: string | null;
        };
        /** Option */
        Option: {
            /** Code */
            code: string;
            /** Label */
            label: string;
        };
        /** OrganizationOut */
        OrganizationOut: {
            /** Address */
            address: string | null;
            /** Gstin */
            gstin: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Personal */
            is_personal: boolean;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** State Code */
            state_code: string | null;
        };
        /** OrganizationPatch */
        OrganizationPatch: {
            /** Address */
            address?: string | null;
            /** Gstin */
            gstin?: string | null;
            /** Name */
            name?: string | null;
            /** State Code */
            state_code?: string | null;
        };
        /** ParamIn */
        ParamIn: {
            /** Unit */
            unit?: string | null;
            /**
             * Value
             * @description Number; strings keep full precision
             */
            value?: string | number | null;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Client Department */
            client_department?: string | null;
            /** Contractor Name */
            contractor_name?: string | null;
            /** Description */
            description?: string | null;
            /** District */
            district?: string | null;
            /** Engineer Name */
            engineer_name?: string | null;
            /** Estimated Value */
            estimated_value?: number | string | null;
            /** Location */
            location?: string | null;
            /** Name */
            name: string;
            /** Project Date */
            project_date?: string | null;
            /**
             * Project Type
             * @enum {string}
             */
            project_type: "building" | "road" | "drain" | "culvert" | "bridge" | "irrigation" | "canal" | "tank" | "lift_irrigation" | "water_supply" | "sewerage" | "electrical" | "other";
            /** Reference Number */
            reference_number?: string | null;
            /**
             * State
             * @default Telangana
             */
            state: string;
            /** Work Category Id */
            work_category_id?: string | null;
        };
        /** ProjectOut */
        ProjectOut: {
            /** Client Department */
            client_department: string | null;
            /** Contractor Name */
            contractor_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** District */
            district: string | null;
            /** Engineer Name */
            engineer_name: string | null;
            /** Estimated Value */
            estimated_value: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Location */
            location: string | null;
            /** My Role */
            my_role: string;
            /** Name */
            name: string;
            /** Project Date */
            project_date: string | null;
            /** Project Type */
            project_type: string;
            /** Project Type Label */
            project_type_label: string;
            /** Reference Number */
            reference_number: string | null;
            /** State */
            state: string;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Work Category Id */
            work_category_id: string | null;
        };
        /** ProjectPage */
        ProjectPage: {
            /** Data */
            data: components["schemas"]["ProjectOut"][];
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** ProjectPatch */
        ProjectPatch: {
            /** Client Department */
            client_department?: string | null;
            /** Contractor Name */
            contractor_name?: string | null;
            /** Description */
            description?: string | null;
            /** District */
            district?: string | null;
            /** Engineer Name */
            engineer_name?: string | null;
            /** Estimated Value */
            estimated_value?: number | string | null;
            /** Location */
            location?: string | null;
            /** Name */
            name?: string | null;
            /** Project Date */
            project_date?: string | null;
            /** Project Type */
            project_type?: ("building" | "road" | "drain" | "culvert" | "bridge" | "irrigation" | "canal" | "tank" | "lift_irrigation" | "water_supply" | "sewerage" | "electrical" | "other") | null;
            /** Reference Number */
            reference_number?: string | null;
            /** State */
            state?: string | null;
            /** Status */
            status?: ("draft" | "in_progress" | "completed" | "archived") | null;
            /** Work Category Id */
            work_category_id?: string | null;
        };
        /** RegisterIn */
        RegisterIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** Password */
            password: string;
        };
        /** ResetIn */
        ResetIn: {
            /** Password */
            password: string;
            /** Token */
            token: string;
        };
        /** ResolvedInputOut */
        ResolvedInputOut: {
            /** Formula Unit */
            formula_unit: string | null;
            /** Formula Value */
            formula_value: string;
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** Source */
            source: string;
            /** Unit */
            unit: string | null;
            /** Value */
            value: string;
        };
        /** StepOut */
        StepOut: {
            /** Kind */
            kind: string;
            /** Text */
            text: string;
        };
        /** SubscriptionOut */
        SubscriptionOut: {
            /**
             * Current Period End
             * Format: date-time
             */
            current_period_end: string;
            /** Features */
            features: {
                [key: string]: unknown;
            };
            /** Limits */
            limits: {
                [key: string]: unknown;
            };
            /** Plan Code */
            plan_code: string;
            /** Plan Name */
            plan_name: string;
            /** Status */
            status: string;
        };
        /** SystemInfo */
        SystemInfo: {
            /** Ai Provider */
            ai_provider: string;
            /** Engine Version */
            engine_version: string;
            /** Environment */
            environment: string;
            /** Google Login Enabled */
            google_login_enabled: boolean;
        };
        /** TemplateOut */
        TemplateOut: {
            /** Category */
            category: string;
            /** Description */
            description: string;
            /** Expression */
            expression: string;
            /** Expression Display */
            expression_display: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Output Unit */
            output_unit: string;
            /** Output Unit Display */
            output_unit_display: string;
            /** Parameters */
            parameters: components["schemas"]["TemplateParameterOut"][];
            /** Version */
            version: number;
        };
        /** TemplateParameterOut */
        TemplateParameterOut: {
            /** Canonical Unit */
            canonical_unit: string | null;
            /** Default */
            default: string | null;
            /** Dimension */
            dimension: string;
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** Required */
            required: boolean;
        };
        /** TokenIn */
        TokenIn: {
            /** Token */
            token: string;
        };
        /** UnitOut */
        UnitOut: {
            /** Aliases */
            aliases: string[];
            /** Code */
            code: string;
            /** Decimal Places */
            decimal_places: number;
            /** Dimension */
            dimension: string;
            /** Display Name */
            display_name: string;
            /** Is Canonical */
            is_canonical: boolean;
        };
        /** UsageOut */
        UsageOut: {
            /** Ai Generations */
            ai_generations: number;
            /** Projects */
            projects: number;
        };
        /** UserOut */
        UserOut: {
            /** Email */
            email: string;
            /** Email Verified */
            email_verified: boolean;
            /** Full Name */
            full_name: string;
            /** Has Password */
            has_password: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Locale */
            locale: string;
            /** Phone */
            phone: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    forgot_password_api_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Message_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MeOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Message_"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Message_"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MeOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_verification_api_v1_auth_resend_verification_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Message_"];
                };
            };
        };
    };
    reset_password_api_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Message_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_email_api_v1_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Message_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_api_v1_calculate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalculateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_CalculationOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_expression_api_v1_calculate_validate_expression_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpressionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ExpressionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_v1_calculation_templates_get: {
        parameters: {
            query?: {
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_TemplateOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_v1_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DashboardOut_"];
                };
            };
        };
    };
    get_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MeOut_"];
                };
            };
        };
    };
    patch_me_api_v1_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MeOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_organization_api_v1_organizations__org_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_OrganizationOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_organization_api_v1_organizations__org_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_OrganizationOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_types_api_v1_project_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_Option__"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: {
                q?: string | null;
                status?: ("draft" | "in_progress" | "completed" | "archived") | null;
                type?: ("building" | "road" | "drain" | "culvert" | "bridge" | "irrigation" | "canal" | "tank" | "lift_irrigation" | "water_supply" | "sewerage" | "electrical" | "other") | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProjectOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProjectOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_v1_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_dict_str__bool__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_project_api_v1_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProjectOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_info_api_v1_system_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SystemInfo_"];
                };
            };
        };
    };
    list_units_api_v1_units_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_UnitOut__"];
                };
            };
        };
    };
    convert_units_api_v1_units_convert_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConvertIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ConvertOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    work_categories_api_v1_work_categories_get: {
        parameters: {
            query?: {
                project_type?: ("building" | "road" | "drain" | "culvert" | "bridge" | "irrigation" | "canal" | "tank" | "lift_irrigation" | "water_supply" | "sewerage" | "electrical" | "other") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_CategoryOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
